version: "3.7"

services:
    db:
        container_name: postgres
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    web:
        container_name: django
        build:
            context: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            SECRET_KEY: ${SECRET_KEY}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: ${DATABASE_HOST}
            DJANGO_SETTINGS_MODULE: app.settings.dev
        volumes:
            - ./backend:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
volumes:
    postgres_data: